# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title: "Guanyu Hu (胡冠宇)"
description: "Personal website of Guanyu Hu (胡冠宇), PhD researcher in Queen Mary University of London (QMUL) and Xi'An Jiaotong University (XJTU)."
repository: "imhgy/imhgy.github.io"
url: "https://www.guanyuhu.com/"

# google analytics
google_analytics_id: G-GPPXHRC911

# SEO Related
google-site-verification: uZIJ0Ocd1rC4zg3-8xvbvqBDJxwmI-Wnpv1-dnDCQQ4
bing_site_verification:  FA9AD1323F684700333A43B938006C24
baidu_site_verification:  codeva-nLInBejYmv

# Site Author
author:
  name: "Guanyu Hu"
  avatar: "images/android-chrome-512x512.jpg"
  university: "QMUL & XJTU"
  location: "London, UK"
  googlescholar: "https://scholar.google.com/citations?user=AxO-zOEAAAAJ&hl=en"
  email: "g.hu@qmul.ac.uk"
  researchgate: "https://www.researchgate.net/profile/Guanyu_Hu8?ev=hdr_xprf"
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: # e.g., "github username"
  google_plus:
  keybase:
  instagram:
  impactstory: # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm:
  linkedin: # e.g., "linkedin username"
  dblp: # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid: # e.g., "https://orcid.org/xxxx"
  pinterest:
  soundcloud:
  stackoverflow: # http://stackoverflow.com/users/123456/username
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Europe/London # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
